version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network


  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - app

  db:
    image: mysql:latest
    container_name: abonnement_db
    environment:
      MYSQL_DATABASE: abonnement
      MYSQL_USER: forester
      MYSQL_PASSWORD: forester
      MYSQL_ROOT_PASSWORD: forester
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network


networks:
  laravel_network:

volumes:
  dbdata:
